### ISSUE TITLE
Error with rest.py

### ISSUE THREAD

**Issue by azzab80** [erikcw/pycirculate#7]
Getting the following error when trying to launch to rest.py

Spent a few hours trying to debug but my python skills are non-existent. Thanks

`pi@mediapi:/usr/local/lib/python2.7/dist-packages/pycirculate $ python ./example/rest/rest.py
Traceback (most recent call last):
  File "./example/rest/rest.py", line 263, in <module>
    main()
  File "./example/rest/rest.py", line 251, in main
    app.anova_controller = RESTAnovaController(ANOVA_MAC_ADDRESS, logger=app.logger)
  File "./example/rest/rest.py", line 43, in __init__
    super(RESTAnovaController, self).__init__(mac_address, connect=connect)
TypeError: __init__() got an unexpected keyword argument 'connect'
`

**Comment by azzab80** [comment]
Sorted it out doing a manual clone from Git
